version: '3'
services:

  # Node app Container
  docker-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  
  # Mongo DB Container
  mongo-app-db:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: