version: '3'
services:
  simple-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - simple-app
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=burhan
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    

volumes:
  mongo-db: